import type { KnowledgeItem } from "../../domain/card";
import { defineTenant } from "../defineTenant";

const assetBase = import.meta.env.BASE_URL.replace(/\/?$/, "/");
const asset = (fileName: string) => `${assetBase}tenants/tuotu/assets/${fileName}`;

const knowledgeBase: KnowledgeItem[] = [
  {
    id: "overview",
    question: "拓浙 AI 生态是什么？",
    shortQuestion: "这是做什么的？",
    answer:
      "拓浙 AI 生态由拓途浙享网站、学习与项目执行体系、浙客松品牌活动及产学合作路径组成。它希望让学生从 AI 学习进入真实项目，并沉淀可展示的成果。",
    keywords: ["是什么", "介绍", "做什么", "拓浙", "生态", "定位"],
    source: "2026 年 7 月规划稿 P010-P016、T03-T04",
  },
  {
    id: "platform",
    question: "拓途浙享网站有什么作用？",
    shortQuestion: "网站有哪些能力？",
    answer:
      "网站是生态的数字入口。现有资料展示了校园活动聚合与 AI 社区界面，并规划项目广场和黑客松成果页，用于发现机会、沉淀内容、组织项目和展示成果。",
    keywords: ["网站", "平台", "能力", "活动", "社区", "功能", "拓途浙享"],
    source: "2026 年 7 月规划稿 P017-P039；规划书(3)产品截图",
  },
  {
    id: "beginner",
    question: "零基础学生可以参加吗？",
    shortQuestion: "零基础怎么加入？",
    answer:
      "可以。学习体系规划提供 AI 工具、AI 编程、智能体入门、低门槛工作坊和基础项目训练。具体课程、招新与报名时间仍需以项目方当期通知为准。",
    keywords: ["零基础", "新手", "文科", "学习", "课程", "怎么加入", "报名"],
    source: "2026 年 7 月规划稿 P043-P051",
  },
  {
    id: "technical",
    question: "有技术基础的学生能做什么？",
    shortQuestion: "技术同学怎么参与？",
    answer:
      "可以关注技术交流、项目组队、真实课题和浙客松。规划中的技术层面向具备开发、产品或协作能力的学生，具体选拔与任务以当期项目要求为准。",
    keywords: ["技术", "开发", "编程", "项目", "组队", "参与", "高手"],
    source: "2026 年 7 月规划稿 P052-P059",
  },
  {
    id: "hackathon",
    question: "浙客松是什么？",
    shortQuestion: "介绍一下浙客松",
    answer:
      "浙客松是围绕 AI 全栈技术和真实场景问题进行项目闭环的系列活动。材料记录首届约 300 人报名、100 人参赛，并规划医学、量化、硬件、旅游、教育和企业服务等主题。",
    keywords: ["浙客松", "黑客松", "比赛", "赛事", "主题", "参赛"],
    source: "2026 年 7 月规划稿 P070-P093、P110",
  },
  {
    id: "cooperation",
    question: "企业如何合作？",
    shortQuestion: "企业如何合作？",
    answer:
      "材料规划企业可提供真实需求、项目或赛题，参与成果评价与人才交流。具体费用、周期、知识产权、保密和验收方式尚未提供，需要由项目方进一步确认。",
    keywords: ["企业", "合作", "商务", "项目需求", "赛题", "共建", "人才"],
    source: "2026 年 7 月规划稿 P060-P067、P083-P087、T06",
  },
  {
    id: "metrics",
    question: "平台目前规模如何？",
    shortQuestion: "平台规模多大？",
    answer:
      "据 2026 年 7 月项目材料，平台注册用户 2300+、日均浏览 900+ 人次、累计收录 700+ 项校园活动，AI 微信交流群达到 500 人满额。这些不是实时接口数据，正式发布前需要复核统计口径。",
    keywords: ["规模", "数据", "用户", "浏览", "活动", "社群", "多少人"],
    source: "2026 年 7 月规划稿 P105-P112",
  },
  {
    id: "official",
    question: "这是浙江大学官方平台吗？",
    shortQuestion: "这是官方平台吗？",
    answer:
      "现有资料只描述以浙江大学为起点及相关校内支持，没有提供足以证明官方主体身份或官方授权的文件。正式身份应以项目方和相关单位确认的信息为准。",
    keywords: ["官方", "浙江大学", "浙大", "隶属", "认证", "授权"],
    source: "2026 年 7 月规划稿 P003、P011、P111-P112",
  },
  {
    id: "opportunity",
    question: "是否保证实习、内推或就业？",
    shortQuestion: "会保证实习吗？",
    answer:
      "不保证。资料表达的是择优连接相关机会，最终结果取决于合作方规则、项目表现和后续评估。样板不会作出录用、内推或就业结果承诺。",
    keywords: ["保证", "实习", "内推", "就业", "校招", "录用", "工作"],
    source: "2026 年 7 月规划稿 P083-P087、T06",
  },
  {
    id: "contact",
    question: "如何加入或联系项目方？",
    shortQuestion: "怎么联系项目方？",
    answer:
      "现有资料没有提供可公开的联系人、电话、邮箱或正式入群入口。你可以先访问 tuotuzju.com 了解公开信息，正式数智名片上线前仍需项目方补齐官方联系渠道。",
    keywords: ["联系", "电话", "邮箱", "微信", "加入", "入群", "地址", "客服"],
    source: "三份项目资料联系人盘点；官网公开入口",
  },
];

export const tuotuTenant = defineTenant({
  id: "tuotu",
  version: "2026.07-v0.1",
  seo: {
    title: "拓浙 AI 生态 | 数智名片",
    description: "拓浙 AI 生态项目数智名片，介绍平台、学习体系、浙客松与产学合作路径。",
  },
  brand: {
    name: "拓浙 AI 生态",
    shortName: "拓浙",
    tagline: "数字艺术与科技",
    headerDescriptor: "数智名片样板",
    logo: {
      src: asset("tuotu-logo.webp"),
      alt: "",
      width: 191,
      height: 192,
    },
    homeAriaLabel: "返回拓浙 AI 生态首页",
    officialAction: {
      kind: "external",
      label: "官网",
      target: "https://tuotuzju.com",
    },
  },
  theme: {
    defaultMode: "system",
    action: "#64e3f6",
    onAction: "#041014",
    light: {
      accent: "#006f84",
      accentStrong: "#005f72",
      accentSoft: "rgba(8, 155, 181, 0.12)",
      background: "#f1f4f5",
      surface: "#fbfcfc",
      surfaceRaised: "#f6f9fa",
      surfaceMuted: "#e8edef",
      text: "#0a1720",
      textSoft: "#54636b",
      textFaint: "#5b6a72",
      line: "rgba(10, 23, 32, 0.13)",
      lineStrong: "rgba(10, 23, 32, 0.22)",
      shadow: "0 28px 80px rgba(24, 43, 53, 0.12)",
    },
    dark: {
      accent: "#48d7ee",
      accentStrong: "#8be8f6",
      accentSoft: "rgba(72, 215, 238, 0.12)",
      background: "#071017",
      surface: "#0d1921",
      surfaceRaised: "#12212a",
      surfaceMuted: "#172730",
      text: "#f4f8fa",
      textSoft: "#a7b5bc",
      textFaint: "#7d8d96",
      line: "rgba(211, 236, 242, 0.14)",
      lineStrong: "rgba(211, 236, 242, 0.24)",
      shadow: "0 28px 90px rgba(0, 0, 0, 0.34)",
    },
    heroOverlay: {
      light: "rgba(238, 243, 245, 0.14)",
      dark: "rgba(2, 10, 17, 0.28)",
    },
    radiusCard: "24px",
    radiusControl: "999px",
    radiusSmall: "12px",
  },
  hero: {
    id: "top",
    kicker: "拓浙 AI 生态项目名片",
    titleLines: ["让 AI 学习", "进入真实项目"],
    summary: "从校园信息入口出发，连接学习、项目、赛事与产学合作。",
    art: {
      src: asset("hero-ecosystem.webp"),
      alt: "",
      width: 1717,
      height: 916,
    },
    actions: [
      { kind: "anchor", label: "探索生态", target: "#ecosystem" },
      { kind: "anchor", label: "查看合作路径", target: "#cooperation" },
    ],
    metrics: [
      { value: "2300+", label: "注册用户", note: "项目材料统计" },
      { value: "900+", label: "日均浏览人次", note: "统计口径待复核" },
      { value: "700+", label: "累计校园活动", note: "项目材料统计" },
      { value: "500", label: "AI 社群满额", note: "2026 年 7 月口径" },
    ],
  },
  sections: [
    {
      type: "feature-grid",
      id: "ecosystem",
      navLabel: "生态",
      showInNav: true,
      heading: "不是一个孤立网站，而是一条成长链路",
      description: "数字平台承接流量与内容，学习体系组织能力成长，浙客松让真实问题变成可见成果。",
      businesses: [
        {
          icon: "globe",
          eyebrow: "数字底座",
          title: "拓途浙享网站",
          description: "从校园活动入口出发，长期沉淀 AI 内容、项目与赛事成果。",
          status: "已有产品界面",
          points: ["活动聚合", "AI 社区", "项目广场规划", "赛事成果库规划"],
        },
        {
          icon: "path",
          eyebrow: "学习体系",
          title: "智能体学习体系",
          description: "让零基础学生进入学习，让技术学生进入真实项目执行。",
          status: "规划体系",
          points: ["新手训练", "技术分层", "项目执行", "成果展示"],
        },
        {
          icon: "rocket",
          eyebrow: "品牌活动",
          title: "浙客松系列活动",
          description: "围绕真实场景，在限定时间内完成 AI 项目闭环。",
          status: "已有首届材料",
          points: ["跨学科主题", "企业题目", "人才观察", "赛后续作"],
        },
      ],
    },
    {
      type: "media-showcase",
      id: "platform",
      navLabel: "平台",
      showInNav: true,
      heading: "先把分散的信息，变成可进入的机会",
      description: "拓途浙享从活动聚合切入，再把用户带向 AI 内容、社区交流与项目实践。",
      capabilities: [
        {
          icon: "calendar",
          title: "活动聚合",
          description: "通知、讲座、竞赛、志愿与招新等分类入口",
        },
        {
          icon: "book",
          title: "内容沉淀",
          description: "教程、工具、技术文章、问答与项目动态",
        },
        {
          icon: "code",
          title: "项目入口",
          description: "项目广场与成果库属于 2026 年 7 月规划能力",
        },
      ],
      action: {
        kind: "external",
        label: "查看当前活动页",
        target: "https://tuotuzju.com/events",
      },
      visualLabel: "来自项目资料",
      visualTitle: "资料内嵌产品界面",
      visual: {
        src: asset("platform-events.webp"),
        alt: "拓途浙享活动聚合界面，包含活动分类、学院筛选、活动卡片和 AI 活动助手",
        caption: "规划书(3)内嵌截图。界面状态不等于所有功能已在生产环境开放。",
        width: 2048,
        height: 1043,
      },
    },
    {
      type: "process",
      id: "journey",
      navLabel: "成长",
      showInNav: true,
      eyebrow: "成长路径",
      heading: "从旁观 AI，到能用 AI 做事",
      description: "同一条路径同时容纳零基础入门和技术型学生，重点是把学习带进真实问题。",
      steps: [
        { title: "发现", text: "从活动与公开资源找到适合自己的入口。" },
        { title: "学习", text: "按基础进入工具、编程或智能体训练。" },
        { title: "实战", text: "加入团队，在项目或浙客松中解决真实问题。" },
        { title: "沉淀", text: "把过程、作品与评价转化为可展示成果。" },
        { title: "连接", text: "择优连接后续项目、实习与孵化机会。" },
      ],
      audienceHeading: "三个入口，一套协作语言",
      audiences: [
        {
          icon: "student",
          title: "学生",
          description: "学习路径、真实项目、作品沉淀与后续机会。",
        },
        {
          icon: "buildings",
          title: "企业与课题方",
          description: "提交真实问题，观察能力，验证 AI 场景。",
        },
        {
          icon: "users",
          title: "学院与组织",
          description: "共建活动、组织学习，沉淀可复用育人案例。",
        },
      ],
    },
    {
      type: "evidence",
      id: "hackathon",
      navLabel: "浙客松",
      showInNav: true,
      heading: "把一场比赛，沉淀成长期成果",
      description: "浙客松被规划为真实问题驱动的系列活动。网站负责传播与沉淀，社区负责学习与组队，项目体系承接赛后续作。",
      visual: {
        src: asset("hackathon-group.webp"),
        alt: "AI 全栈极速黑客松活动现场合影，参与者在会场屏幕前合照",
        caption: "内测素材。公开发布前需确认活动图片和人物肖像授权。",
        width: 1379,
        height: 744,
      },
      headlineMetric: "300 / 100",
      metricDescription: "材料记录：约 300 人报名，100 人参赛",
      themesAriaLabel: "规划主题方向",
      themes: ["AI + 医学", "AI + 量化", "AI + 硬件", "AI + 旅游", "AI + 教育", "AI + 企业服务"],
      caveat: "“季度化”“首个”“绿色通道”等表述在正式发布前仍需佐证。",
      supportHeading: "项目材料所述支持方",
      supportNote: "名称与称谓正式发布前逐项确认",
      supportNames: ["阿里云", "MiniMax", "魔搭社区", "阶跃星辰", "Qoder", "Bonjour"],
    },
    {
      type: "engagement",
      id: "cooperation",
      navLabel: "合作",
      showInNav: true,
      heading: "让真实需求，成为学生的项目现场",
      description: "合作不是简单发布题目，而是先把边界、交付和评价方式讲清楚。",
      steps: [
        { title: "提交需求", text: "提供真实业务问题、课题或赛事方向。" },
        { title: "筛选拆解", text: "明确边界、交付物、周期与评价方式。" },
        { title: "匹配团队", text: "按能力和兴趣组织学生项目团队。" },
        { title: "执行评价", text: "在项目或赛事中形成作品与阶段结果。" },
        { title: "后续连接", text: "根据真实表现讨论续作、人才或孵化机会。" },
      ],
      cta: {
        title: "先用资料助手了解合作边界",
        description: "正式版需补充联系人、费用、知识产权、保密和验收条款。",
        action: { kind: "assistant", label: "询问合作细节", target: "企业如何合作？" },
      },
    },
    {
      type: "faq",
      id: "faq",
      navLabel: "FAQ",
      showInNav: true,
      eyebrow: "常见问题",
      heading: "先把关键问题说明白",
      description: "每个回答都有材料来源。资料没有覆盖的问题，助手会明确拒绝猜测。",
      itemIds: ["overview", "beginner", "hackathon", "cooperation", "official", "opportunity"],
    },
    {
      type: "closing",
      id: "closing",
      navLabel: "收束",
      showInNav: false,
      heading: "从一份企业资料，生成一张会讲解的数智名片",
      description: "",
      art: {
        src: asset("hero-ecosystem.webp"),
        alt: "",
        width: 1717,
        height: 916,
      },
      actions: [
        { kind: "assistant", label: "向资料助手提问", target: "open" },
      ],
    },
  ],
  assistant: {
    title: "拓浙资料助手",
    status: "演示",
    subtitle: "本地知识库 · 不连接外部模型",
    launcherAriaLabel: "打开拓浙 AI 资料助手",
    launcherKicker: "资料内回答",
    launcherLabel: "问 AI 助手",
    initialMessage: {
      text: "你好，我是拓浙 AI 生态资料助手。当前为本地知识库演示，只回答已核验的项目资料。",
      source: "样板知识库 v2026.07",
    },
    quickQuestionIds: ["overview", "beginner", "cooperation"],
    labels: {
      closeBackdrop: "关闭 AI 助手",
      closeButton: "关闭助手",
      quickQuestions: "常见问题",
      quickQuestionsIntro: "可以先问",
      loading: "正在检索资料",
      input: "向资料助手提问",
      placeholder: "问业务、学习、赛事或合作",
      send: "发送问题",
      sourcePrefix: "来源：",
    },
    disclaimer: "回答来自 2026 年 7 月样板资料，不代表实时承诺。",
    knowledgeBase,
    fallback: {
      answer:
        "这份项目资料暂未覆盖这个问题，我不能根据猜测补充。你可以换个问法，或访问 tuotuzju.com 查看项目方公开信息。正式版还需要配置人工联系入口。",
      source: "资料边界规则",
    },
  },
  footer: {
    brandNote: "创非凡企业数智名片样板",
    disclaimer: "本页为内部演示，企业主体、联系方式、数据口径与素材授权待项目方终审。",
    backToTopAction: { kind: "anchor", label: "返回顶部", target: "#top" },
  },
});
